<a href="https://colab.research.google.com/github/camila-galindo/eda-teraverso/blob/main/Desafio_Tera_Analise_Explorat%C3%B3ria_de_dados_Teraverso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing the Python libraries

In [ ]:
import pandas as pd #library for data manipulation and analysis.
import numpy as np #library for scientific computing with Python.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
file_path = '/content/drive/MyDrive/Educação - Cursos/Tera - Data Analytics/Desafio Tera - Analise Exploratória de dados Teraverso/dataset1.csv'

In [ ]:
df = pd.read_csv(file_path, encoding='latin-1')

### Commits

### Understanding the Dataset

**Perguntas de negócio que precisamos responder**
-

**Perguntas iniciais para investigação do dataset**
- Quais são as features?
- Quais são os tipos dos dados? Entendemos que esse tipo faz sentido?
- Existem dados nulos?
-

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               106 non-null    int64
 1   Name             105 non-null    object
 2   Platform         97 non-null     object
 3   Year_of_Release  105 non-null    object
 4   Genre            105 non-null    object
 5   Publisher        105 non-null    object
 6   NA_Sales         105 non-null    object
 7   EU_Sales         105 non-null    object
 8   JP_Sales         101 non-null    object
 9   Other_Sales      105 non-null    object
 10  Global_Sales     77 non-null     object
dtypes: int64(1), object(10)
memory usage: 9.2+ KB

**Notas:**
- Apenas o `Id` é um campo que não contem valores nulos.
- Year_of_Release deveria ser do tipo object?
- Se `Global_Sales` representa a soma de todas as vendas, deveriamos ter valores nulos?

In [ ]:
df.head()

,Id,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,NaN,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,NaN,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52
3,4,Wii Sports Resort,NaN,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,"1,0",31.37

In [ ]:
df.isna().sum()

Id                  0
Name                1
Platform            9
Year_of_Release     1
Genre               1
Publisher           1
NA_Sales            1
EU_Sales            1
JP_Sales            5
Other_Sales         1
Global_Sales       29
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Id,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,NaN,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53
2,3,Mario Kart Wii,NaN,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52
3,4,Wii Sports Resort,NaN,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77
7,8,Wii Play,NaN,2006,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92
8,9,New Super Mario Bros. Wii,NaN,2009,Platform,Nintendo,14.44,6.94,4.7,2.24,28.32
10,11,Nintendogs,DS,2005,Simulation,Ñintendo,9.05,10.95,1.93,2.74,NaN
13,14,Wii Fit,NaN,2007,Sports,Nintendo,8.92,8.03,3.6,2.15,22.7
15,16,Wii Fit Plus,NaN,2009,Sports,Nintendo,9.01,8.49,2.53,1.77,"21,79"
21,21,Pokemon Diamond/Pokemon Pearl,DS,2006,Role-Playing,Nintendo,6.38,4.46,6.04,1.36,NaN
22,22,Super Mario Land,GB,1989,Platform,Nintendo,10.83,2.71,4.18,0.42,NaN
42,42,Call of Duty: Black Ops,PS3,2010,Shooter,Activision,5.99,4.37,0.48,1.79,NaN
43,43,Grand Theft Auto V,PS4,2014,Action,Take-Two Interactive,3.96,6.31,0.38,1.97,NaN
44,44,Animal Crossing: Wild World,DS,2005,Simulation,Nintendo,2.5,3.45,5.33,0.86,NaN
45,45,Halo 3,X3600000,2007,Shooter,Microsoft Game Studios,7.97,2.81,0.13,1.21,NaN
46,46,Super Mario 64,N64,1996,Platform,NINTENDO,6.91,2.85,1.91,0.23,NaN
63,62,Just Dance 3,Wii,2011,Misc,Ubisoft,5.95,3.11,NaN,1.06,10.12
74,73,Minecraft,X360,2013,Misc,Microsoft Game Studios,5.7,2.65,0.02,0.81,NaN
75,74,Animal Crossing: New Leaf,3DS,2012,Simulation,Nintendo,2.03,2.36,4.39,0.39,NaN
76,75,Mario Party DS,DS,2007,Misc,Nintendo,4.4,1.85,1.98,0.68,NaN
77,76,The Elder Scrolls V: Skyrim,X360,2011,Role-Playing,Bethesda Softworks,5.05,2.79,0.1,0.85,NaN
78,77,Super Mario Kart,SNES,1992,Racing,Nintendo,3.54,1.24,3.81,0.18,NaN
79,78,FIFA 16,PS4,2015,Sports,Electronic Arts,1.12,6.12,0.06,1.28,NaN
80,78,FIFA 16,PS4,2015,Sports,Electronic Arts,1.12,6.12,0.06,1.28,NaN
81,78,FIFA 16,PS4,2015,Sports,Electronic Arts,1.12,6.12,0.06,1.28,NaN
82,79,Halo 2,XB,1804,Shooter,Microsoft Game Studios,6.82,1.53,0.05,0.08,NaN
83,80,Wii Party,NaN,2010,Misc,Nintendo,1.75,3.47,2.49,0.67,NaN
86,83,GoldenEye 007,N64,1997,Shooter,nintendo,5.8,2.01,0.13,0.15,NaN
87,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,86,The Sims 3,PC,2009,Simulation,Electronic Arts,0.99,6.42,NaN,0.6,8.01
91,86,The Sims 3,PC,2009,Simulation,Electronic Arts,0.99,6.42,NaN,0.6,8.01
92,87,Mario & Sonic at the Olympic Games,Wii,2007,Sports,Sega,2.57,3.86,0.66,0.91,NaN
93,88,Star Wars Battlefront (2015),PS4,2015,Shooter,Electronic Arts,2.99,3.49,0.22,1.28,NaN
94,89,Final Fantasy VIII,PS,1999,Role-Playing,SquareSoft,2.28,1.72,3.63,0.23,NaN
95,90,Pac-Man,2600,1982,Puzzle,Atari,7.28,0.45,NaN,0.08,NaN
96,91,PokÃ©mon Platinum Version,DS,2008,Role-Playing,Nintendo,2.76,1.72,2.69,0.54,NaN
97,92,Grand Theft Auto: Liberty City Stories,PSP,2005,Action,Take-Two Interactive,2.9,2.81,0.24,1.73,NaN
101,96,Crash Bandicoot 2: Cortex Strikes Back,PS,1997,Platform,Sony Computer Entertainment,3.78,2.17,1.31,0.31,NaN
102,97,Super Smash Bros. for Wii U and 3DS,3DS,2014,Fighting,Nintendo,3.27,1.37,2.43,0.48,NaN
103,98,Super Mario Galaxy 2,Wii,2010,Platform,Nintendo,3.56,2.35,0.98,0.62,NaN

**Notas:**
- Podemos encontrar um padrão para preencher os nomes das plataformas que estão nulos?

### Validação dos dados e entendimento das variáveis do Dataset

In [ ]:
df['Id'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 106 entries, 0 to 105
Series name: Id
Non-Null Count  Dtype
--------------  -----
106 non-null    int64
dtypes: int64(1)
memory usage: 976.0 bytes

In [ ]:
sorted(df['Name'].unique().astype(str))

['Animal Crossing: New Leaf',
 'Animal Crossing: Wild World',
 'Brain Age 2: More Training in Minutes a Day',
 'Brain Age: Train Your Brain in Minutes a Day',
 'Call of Duty 4: Modern Warfare',
 'Call of Duty: Advanced Warfare',
 'Call of Duty: Black Ops',
 'Call of Duty: Black Ops 3',
 'Call of Duty: Black Ops II',
 'Call of Duty: Ghosts',
 'Call of Duty: Modern Warfare 2',
 'Call of Duty: Modern Warfare 3',
 'Crash Bandicoot 2: Cortex Strikes Back',
 'Donkey Kong Country',
 'Duck Hunt',
 'FIFA 16',
 'FIFA 17',
 'FIFA Soccer 13',
 'Final Fantasy VII',
 'Final Fantasy VIII',
 'Final Fantasy X',
 'GoldenEye 007',
 'Gran Turismo',
 'Gran Turismo 2',
 'Gran Turismo 3: A-Spec',
 'Gran Turismo 4',
 'Gran Turismo 5',
 'Grand Theft Auto III',
 'Grand Theft Auto IV',
 'Grand Theft Auto V',
 'Grand Theft Auto: Liberty City Stories',
 'Grand Theft Auto: San Andreas',
 'Grand Theft Auto: Vice City',
 'Halo 2',
 'Halo 3',
 'Halo 4',
 'Halo: Reach',
 'Just Dance 2',
 'Just Dance 3',
 'Kinect Adventures!',
 'Mario & Sonic at the Olympic Games',
 'Mario Kart 64',
 'Mario Kart 7',
 'Mario Kart DS',
 'Mario Kart Wii',
 'Mario Party 8',
 'Mario Party DS',
 'Minecraft',
 'New Super Mario Bros.',
 'New Super Mario Bros. 2',
 'New Super Mario Bros. Wii',
 'Nintendogs',
 'Pac-Man',
 'Pokemon Black 2/Pokemon White 2',
 'Pokemon Black/Pokemon White',
 'Pokemon Diamond/Pokemon Pearl',
 'Pokemon FireRed/Pokemon LeafGreen',
 'Pokemon Gold/Pokemon Silver',
 'Pokemon HeartGold/Pokemon SoulSilver',
 'Pokemon Omega Ruby/Pokemon Alpha Sapphire',
 'Pokemon Red/Pokemon Blue',
 'Pokemon Ruby/Pokemon Sapphire',
 'Pokemon X/Pokemon Y',
 'PokÃ©mon Platinum Version',
 'PokÃ©mon Yellow: Special Pikachu Edition',
 'Star Wars Battlefront (2015)',
 'Super Mario 3D Land',
 'Super Mario 64',
 'Super Mario All-Stars',
 'Super Mario Bros.',
 'Super Mario Bros. 2',
 'Super Mario Bros. 3',
 'Super Mario Galaxy',
 'Super Mario Galaxy 2',
 'Super Mario Kart',
 'Super Mario Land',
 'Super Mario Land 2: 6 Golden Coins',
 'Super Mario World',
 'Super Smash Bros. Brawl',
 'Super Smash Bros. for Wii U and 3DS',
 'Tetris',
 'The Elder Scrolls V: Skyrim',
 'The Legend of Zelda: Ocarina of Time',
 'The Sims 3',
 'Wii Fit',
 'Wii Fit Plus',
 'Wii Party',
 'Wii Play',
 'Wii Sports',
 'Wii Sports Resort',
 'nan']

In [ ]:
df['Platform'].unique()

array([nan, 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA', 'PS4',
       '3DS', 'Wii', 'X3600000', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP',
       'XOne'], dtype=object)

In [ ]:
df['Publisher'].unique()

array(['Nintendo', 'Ñintendo', 'Microsoft Game Studios',
       'Take-Two Interactive', 'Sony Computer Entertainment',
       'Activision', 'NINTENDO', 'Ubisoft', 'nintendo',
       'Bethesda Softworks', 'Electronic Arts', nan, 'Sega', 'SquareSoft',
       'Atari'], dtype=object)

In [ ]:
df['Year_of_Release'].unique()

array(['2006', '1985', '2008', '2009', '1996', '1989', '1984', '2005',
       '1999', '2007', '2010', '2013', '2004', '1990', '1988',
       '9/17/2013', '2002', '2001', '2011', '1998', '2015', '20100',
       '2012', '2014', '12004', '1992', '1997', '1993', '3007', '1994',
       '1804', nan, '1982', '1948', '2016'], dtype=object)

In [ ]:
df['Genre'].unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure', nan],
      dtype=object)

### Limpeza dos Dados

Id
Name
Platform
Year_of_Release
Genre

#### Publisher

In [ ]:
df['Publisher'].replace('Ñintendo', 'Nintendo', inplace=True)

In [ ]:
df['Publisher'].replace('NINTENDO', 'Nintendo', inplace=True)

In [ ]:
df['Publisher'].replace('nintendo', 'Nintendo', inplace=True)

In [ ]:
df['Publisher'].unique()

array(['Nintendo', 'Microsoft Game Studios', 'Take-Two Interactive',
       'Sony Computer Entertainment', 'Activision', 'Ubisoft',
       'Bethesda Softworks', 'Electronic Arts', nan, 'Sega', 'SquareSoft',
       'Atari'], dtype=object)

#### Year_of_Release

In [ ]:
df['Year_of_Release'].replace('9/17/2013', '2013', inplace=True)
df['Year_of_Release'].fillna(0, inplace=True)

In [ ]:
df[df['Year_of_Release'].isnull()]

Empty DataFrame
Columns: [Id, Name, Platform, Year_of_Release, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales]
Index: []

#### Genre

In [ ]:
df['Genre'].fillna('Not_informed', inplace=True)
df['Genre'].unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Not_informed'], dtype=object)

#### Global_Sales

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
df[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].head(10)

  NA_Sales EU_Sales JP_Sales Other_Sales Global_Sales
0    41.36    28.96     3.77        8.45        82.53
1    29.08     3.58     6.81        0.77        40.24
2    15.68    12.76     3.79        3.29        35.52
3    15.61    10.93     3.28        2.95        32.77
4    11.27     8.89    10.22         1,0        31.37
5     23.2     2.26     4.22        0.58        30.26
6    11.28     9.14      6.5        2.88         29.8
7    13.96     9.18     2.93        2.84        28.92
8    14.44     6.94      4.7        2.24        28.32
9    26.93     0.63     0.28        0.47        28.31

In [ ]:
df['NA_Sales'].fillna(0, inplace=True)
df['EU_Sales'].fillna(0, inplace=True)
df['JP_Sales'].fillna(0, inplace=True)
df['Other_Sales'].fillna(0, inplace=True)
df['Global_Sales'].fillna(0, inplace=True)

In [ ]:
df['NA_Sales'] = df['NA_Sales'].apply(lambda x: float(str(x).replace(',', '.')) if isinstance(x, str) else x).round(2)
df['EU_Sales'] = df['EU_Sales'].apply(lambda x: float(str(x).replace(',', '.')) if isinstance(x, str) else x).round(2)
df['JP_Sales'] = df['JP_Sales'].apply(lambda x: float(str(x).replace(',', '.')) if isinstance(x, str) else x).round(2)
df['Other_Sales'] = df['Other_Sales'].apply(lambda x: float(str(x).replace(',', '.')) if isinstance(x, str) else x).round(2)
df['Global_Sales'] = df['NA_Sales'] + df['EU_Sales'] + df['JP_Sales'] + df['Other_Sales']

#### Geral

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               106 non-null    int64
 1   Name             105 non-null    object
 2   Platform         97 non-null     object
 3   Year_of_Release  106 non-null    object
 4   Genre            106 non-null    object
 5   Publisher        105 non-null    object
 6   NA_Sales         106 non-null    float64
 7   EU_Sales         106 non-null    float64
 8   JP_Sales         106 non-null    float64
 9   Other_Sales      106 non-null    float64
 10  Global_Sales     106 non-null    float64
dtypes: float64(5), int64(1), object(5)
memory usage: 9.2+ KB

In [ ]:
df[df.isnull().any(axis=1)]

,Id,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,NaN,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.54
2,3,Mario Kart Wii,NaN,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52
3,4,Wii Sports Resort,NaN,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77
7,8,Wii Play,NaN,2006,Misc,Nintendo,13.96,9.18,2.93,2.84,28.91
8,9,New Super Mario Bros. Wii,NaN,2009,Platform,Nintendo,14.44,6.94,4.70,2.24,28.32
13,14,Wii Fit,NaN,2007,Sports,Nintendo,8.92,8.03,3.60,2.15,22.70
15,16,Wii Fit Plus,NaN,2009,Sports,Nintendo,9.01,8.49,2.53,1.77,21.80
83,80,Wii Party,NaN,2010,Misc,Nintendo,1.75,3.47,2.49,0.67,8.38
87,83,NaN,NaN,0,Not_informed,NaN,0.00,0.00,0.00,0.00,0.00

In [ ]:
df1 = df.drop(df[df['Id'] == 83].index)

In [ ]:
df1[df1.isnull().any(axis=1)]

,Id,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,NaN,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.54
2,3,Mario Kart Wii,NaN,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52
3,4,Wii Sports Resort,NaN,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77
7,8,Wii Play,NaN,2006,Misc,Nintendo,13.96,9.18,2.93,2.84,28.91
8,9,New Super Mario Bros. Wii,NaN,2009,Platform,Nintendo,14.44,6.94,4.70,2.24,28.32
13,14,Wii Fit,NaN,2007,Sports,Nintendo,8.92,8.03,3.60,2.15,22.70
15,16,Wii Fit Plus,NaN,2009,Sports,Nintendo,9.01,8.49,2.53,1.77,21.80
83,80,Wii Party,NaN,2010,Misc,Nintendo,1.75,3.47,2.49,0.67,8.38

### Análise dos relacionamentos entre as variáveis

### Conclusões e Direcionamentos para os próximos passos